spring:
  application:
    name: service-payment
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

    openfeign:
      lazy-attributes-resolution: true